#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

PADDINGS=3 # All paddings use this value (icon, label, background)
FONT="SF Pro"

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"

# Unload the MacOS on-screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

##### Bar Appearance #####

sketchybar --bar height=39 \
                 color=$BAR_COLOR \
                 shadow=on \
                 position=top \
                 sticky=on \
                 padding_right=10 \
                 padding_left=10 \
                 corner_radius=9 \
                 y_offset=12 \
                 margin=12 \
                 blur_radius=20 \
                 notch_width=0

##### Changing Defaults #####

sketchybar --default updates=when_shown \
                     icon.font="$FONT:Bold:14.0" \
                     icon.color=$ICON_COLOR \
                     icon.padding_left=$PADDINGS \
                     icon.padding_right=$PADDINGS \
                     label.font="$FONT:Semibold:13.0" \
                     label.color=$LABEL_COLOR \
                     label.padding_left=$PADDINGS \
                     label.padding_right=$PADDINGS \
                     padding_left=$PADDINGS \
                     padding_right=$PADDINGS \
                     background.height=30 \
                     background.corner_radius=9 \
                     popup.background.border_width=2 \
                     popup.background.corner_radius=9 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR \
                     popup.background.shadow.drawing=on

# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai_float.sh"
source "$ITEM_DIR/front_app.sh"

# Center
#source "$ITEM_DIR/spotify.sh"

# Right
#source "$ITEM_DIR/github.sh"
#source "$ITEM_DIR/mail.sh"
#source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"

sketchybar --add bracket status '/status\..*/' \
           --set status  background.color=$BACKGROUND_1 \
                         background.border_color=$BACKGROUND_2 \
                         background.border_width=2

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
