# right_format = """
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status"""

[package]
disabled = true

[directory]
truncation_symbol = "…/"

[nodejs]
disabled = false

[ruby]
disabled = true

[java]
disabled = true

[aws]
disabled = true
